#!/bin/sh

# Fullscreen for main monitor

case "$1" in
	"full")
		wtp 0 0 5120 1440 $2
		;;
	"left")
		wtp 0 0 2560 1440 $2
		;;
	"right")
		wtp 2560 0 2560 1440 $2
		;;
	*)
		echo "full left right"
		;;
esac

