#!/bin/bash

file=$(date +"%b-%d-%Y-%R").jpg
dir=~/Screenshot/${file}

case "$1" in
  "Area") import ${dir} ;;
  "Window") import -window $(slw) ${dir} ;;
  "Full") import -window root ${dir};;
  *)echo "Area" "Window" "Full" && exit 1;;
esac

notify-send "Saved at ${dir}"
