#!/bin/bash

get_choice() {
	title=$1
	shift
	echo $(printf '%s\n' "$@" | rofi -dmenu -p "$title")
}

get_YN() {
	get_choice "Are you sure?" "Yes" "No"
}

choice=$1
[[ -z $1 ]] && choice=$(get_choice "Session Menu" "exit session" "startup" "full" "daily preset" "color" "xrdm" "screenshot" "dev" "web" "fetch" "close")

case "$choice" in
	"exit session") 
		[ $(get_YN) == "Yes" ] && killall sxhkd
		;;
	"startup")
		wind &
		;;
	"full")
		fullscreen $(get_choice "To where?" $(fullscreen) "No") $(pfw)
		;;
	"daily preset")
		xrdm preset daily
		;;
	"color")
		xrdm color $(get_choice "color" $(xrdm color))
		;;
	"xrdm")
		case "$(get_choice "xrdm" "color" "font" "program" "preset")" in
			"color")
				xrdm color $(get_choice "color" $(xrdm color))
				;;
			"font")
				xrdm font $(get_choice "font" $(xrdm font))
				;;
			"program")
				xrdm program $(get_choice "program" $(xrdm program))
				;;
			"preset")
				xrdm preset $(get_choice "preset" $(xrdm preset))
				;;
		esac
		;;
  "screenshot")
    screenshot $(get_choice "Method" $(screenshot))
    ;;
	"dev")
		st -e "tmux" &
		sleep 0.1
    session_menu full
		;;
	"web")
		firefox & 
		sleep 0.1
    session_menu full
		;;
	"close")
		killw $(pfw)
		;;
	*) ;;
esac
